[package]
name = "rust-solutions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "1.4.1"
nom = "7.1.3"
num = "0.4.1"
priority-queue = "1.3.2"
rust-analyzer = "0.0.1"
